//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts_discounts
    {
        public int id { get; set; }
        public int acc_id { get; set; }
        public bool ispaidDiscount { get; set; }
        public double amount { get; set; }
        public System.DateTime reg_date { get; set; }
        public int user_id { get; set; }
    
        public virtual account account { get; set; }
        public virtual user user { get; set; }
    }
}
