//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account()
        {
            this.accounts_discounts = new HashSet<accounts_discounts>();
            this.empos = new HashSet<empos>();
        }
    
        public int id { get; set; }
        public string acc_name { get; set; }
        public string acc_phone { get; set; }
        public string acc_address { get; set; }
        public Nullable<double> acc_firstBalance { get; set; }
        public Nullable<bool> acc_debit { get; set; }
        public string acc_type { get; set; }
        public string acc_price { get; set; }
        public string acc_phone2 { get; set; }
        public string acc_phone3 { get; set; }
        public string acc_phone4 { get; set; }
        public string acc_email { get; set; }
        public string acc_email2 { get; set; }
        public string acc_email3 { get; set; }
        public string acc_repr { get; set; }
        public string acc_repr2 { get; set; }
        public string acc_repr3 { get; set; }
        public string acc_address2 { get; set; }
        public string acc_address3 { get; set; }
        public string acc_getcode { get; set; }
        public string descountTyp { get; set; }
        public bool isshown { get; set; }
        public Nullable<double> acc_limit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accounts_discounts> accounts_discounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empos> empos { get; set; }
    }
}
