//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banks_acc_transactions
    {
        public int id { get; set; }
        public int From_bnk_acc_id { get; set; }
        public int To_bnk_acc_id { get; set; }
        public System.DateTime reg_date { get; set; }
        public System.DateTime action_date { get; set; }
        public double amount { get; set; }
        public string nts { get; set; }
        public int usr_id { get; set; }
        public int emp_id { get; set; }
        public int shift_id { get; set; }
    
        public virtual Banks_accounts Banks_accounts { get; set; }
        public virtual Banks_accounts Banks_accounts1 { get; set; }
        public virtual empos empos { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual user user { get; set; }
    }
}
