//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banks_allAccCredit
    {
        public int id { get; set; }
        public string bnk_acc_name { get; set; }
        public double first_balance { get; set; }
        public Nullable<double> su_sal { get; set; }
        public Nullable<double> su_pay_in { get; set; }
        public Nullable<double> su_pay_out { get; set; }
        public Nullable<double> su_pur { get; set; }
        public Nullable<double> su_trns_from { get; set; }
        public Nullable<double> su_trns_to { get; set; }
        public Nullable<double> su_outcome { get; set; }
        public Nullable<double> su_income { get; set; }
        public Nullable<double> su_emps_updwn { get; set; }
        public Nullable<double> final { get; set; }
    }
}
