//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class barcode
    {
        public string barcode1 { get; set; }
        public int item_id { get; set; }
        public int unit_id { get; set; }
    
        public virtual item item { get; set; }
    }
}
