//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class capital
    {
        public int id { get; set; }
        public Nullable<double> amount_cash { get; set; }
        public Nullable<double> amount_cobon { get; set; }
        public string notes { get; set; }
    }
}
