//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSetting
    {
        public string Dname { get; set; }
        public string Ddata { get; set; }
        public string Dname_ar { get; set; }
        public int id { get; set; }
    }
}
