//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class empos_attend
    {
        public int id { get; set; }
        public int emp_id { get; set; }
        public Nullable<System.TimeSpan> t_in { get; set; }
        public Nullable<System.TimeSpan> t_out { get; set; }
        public Nullable<System.TimeSpan> b_in { get; set; }
        public Nullable<System.TimeSpan> b_out { get; set; }
        public Nullable<System.DateTime> dy { get; set; }
        public int user_id { get; set; }
        public Nullable<double> min_pri { get; set; }
        public Nullable<System.DateTime> real_in { get; set; }
        public Nullable<System.DateTime> base_in { get; set; }
        public Nullable<System.DateTime> real_out { get; set; }
        public Nullable<System.DateTime> base_out { get; set; }
        public string notes { get; set; }
        public System.DateTime reg_date { get; set; }
        public bool isConfirmed { get; set; }
        public int brch_id { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual empos empos { get; set; }
    }
}
