//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factory
    {
        public int id { get; set; }
        public string fct_name { get; set; }
        public string fct_address { get; set; }
        public Nullable<int> fct_emp { get; set; }
    }
}
