//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class installment_slrs
    {
        public int id { get; set; }
        public string slr_name { get; set; }
        public string slr_id { get; set; }
        public string slr_phone { get; set; }
        public string slr_address { get; set; }
        public string itm_name { get; set; }
        public string itm_license { get; set; }
        public string itm_chassis { get; set; }
        public System.DateTime dte { get; set; }
    }
}
