//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class installment_TradersMovs
    {
        public int id { get; set; }
        public int trdr_id { get; set; }
        public System.DateTime dte { get; set; }
        public double amount { get; set; }
        public bool isCredit { get; set; }
        public string notes { get; set; }
    }
}
