//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_booking
    {
        public int inv_id { get; set; }
        public string cust { get; set; }
        public string phon { get; set; }
        public Nullable<double> booking_amount { get; set; }
    }
}
