//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items_credits
    {
        public int id { get; set; }
        public string iname { get; set; }
        public string cate { get; set; }
        public string comp { get; set; }
        public Nullable<double> limit { get; set; }
        public Nullable<double> crdt { get; set; }
    }
}
