//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class items_drafts
    {
        public int Id { get; set; }
        public int item_id { get; set; }
        public double price { get; set; }
        public bool isDraft { get; set; }
        public int date { get; set; }
        public int user_id { get; set; }
    }
}
