//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSpeer_response
    {
        public Nullable<int> request_id { get; set; }
        public string peer { get; set; }
        public string peer_db { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
    }
}
