//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSpeer_originatorid_history
    {
        public string originator_publication { get; set; }
        public int originator_id { get; set; }
        public string originator_node { get; set; }
        public string originator_db { get; set; }
        public int originator_db_version { get; set; }
        public int originator_version { get; set; }
        public System.DateTime inserted_date { get; set; }
    }
}
