//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSpeer_topologyrequest
    {
        public int id { get; set; }
        public string publication { get; set; }
        public Nullable<System.DateTime> sent_date { get; set; }
    }
}
