//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSpub_identity_range
    {
        public int objid { get; set; }
        public long range { get; set; }
        public long pub_range { get; set; }
        public long current_pub_range { get; set; }
        public int threshold { get; set; }
        public Nullable<long> last_seed { get; set; }
    }
}
