//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class newcolumn
    {
        public Nullable<long> id { get; set; }
        public string Table_Name { get; set; }
        public string Column_Name { get; set; }
        public string Data_Type { get; set; }
        public string collation_name { get; set; }
        public Nullable<bool> is_nullable { get; set; }
        public short max_length { get; set; }
        public string defaultValue { get; set; }
        public bool is_identity { get; set; }
    }
}
