//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int id { get; set; }
        public int item_id { get; set; }
        public int unit_id { get; set; }
        public double biger_than { get; set; }
        public double price_after { get; set; }
        public System.DateTime start_dte { get; set; }
        public System.DateTime end_dte { get; set; }
        public System.DateTime re_dte { get; set; }
        public int user_id { get; set; }
    }
}
