//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class repre_comm_levels
    {
        public int emp_id { get; set; }
        public decimal big_than { get; set; }
        public decimal comm { get; set; }
    
        public virtual empos empos { get; set; }
    }
}
