//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class repre_months
    {
        public int id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<int> mnth { get; set; }
        public Nullable<int> yer { get; set; }
        public Nullable<double> sales { get; set; }
        public Nullable<double> comm { get; set; }
        public int user_id { get; set; }
        public System.DateTime reg_date { get; set; }
        public int reward_id { get; set; }
    }
}
