//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class representative
    {
        public int emp_id { get; set; }
        public double month_target { get; set; }
        public decimal min_per { get; set; }
        public bool isedit { get; set; }
    
        public virtual empos empos { get; set; }
    }
}
