//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_re_det_pack
    {
        public int inv_id { get; set; }
        public Nullable<int> mitem_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<double> count { get; set; }
    
        public virtual item item { get; set; }
        public virtual item item1 { get; set; }
        public virtual sales_re sales_re { get; set; }
    }
}
