//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocks_Trans
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dat { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string nts { get; set; }
        public Nullable<int> stk_from { get; set; }
        public Nullable<int> stk_to { get; set; }
    }
}
