//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocks_OB
    {
        public Nullable<int> stk_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<double> count { get; set; }
        public Nullable<double> item_limit { get; set; }
        public int unit_id { get; set; }
        public double unit_count { get; set; }
        public double pur_price { get; set; }
    }
}
