//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocks_Trans_det
    {
        public int trns_id { get; set; }
        public int item_id { get; set; }
        public double count { get; set; }
        public Nullable<double> price_pur { get; set; }
        public Nullable<double> price { get; set; }
        public int u_id { get; set; }
        public double u_count { get; set; }
    }
}
