//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tw
    {
        public int id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    }
}
