//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_brchs_lnks
    {
        public int usr_id { get; set; }
        public Nullable<int> brch_id { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual user user { get; set; }
    }
}
