//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class v2
    {
        public string typ { get; set; }
        public Nullable<double> credit { get; set; }
        public Nullable<double> debit { get; set; }
        public Nullable<double> sm { get; set; }
        public Nullable<System.DateTime> action_date { get; set; }
        public string nts { get; set; }
        public Nullable<int> usr_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public int bnk_acc_id { get; set; }
    }
}
