//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class workOrders_v
    {
        public int id { get; set; }
        public string st { get; set; }
        public string fct_name { get; set; }
        public Nullable<System.DateTime> open_date { get; set; }
        public Nullable<System.DateTime> close_date { get; set; }
        public string ename { get; set; }
        public string notes { get; set; }
        public string uName { get; set; }
        public System.DateTime reg_date { get; set; }
        public int fctry_id { get; set; }
        public int emp_id { get; set; }
        public bool status_isOpen { get; set; }
    }
}
