//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testreports.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrders_Current
    {
        public int id { get; set; }
        public int wId { get; set; }
        public int fctry_id { get; set; }
        public string WOName { get; set; }
    }
}
