//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail
    {
        public int Id { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Count { get; set; }
        public Nullable<double> PurPrice { get; set; }
        public Nullable<int> InvId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
