//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierPayment
    {
        public int Id { get; set; }
        public Nullable<int> AccId { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
